site:
  url: https://stephen-cox.github.io/vulnfeed
  github: https://github.com/stephen-cox/vulnfeed

feeds:
  - source: github
    repos:
      - argoproj/argo-cd
      - composer/composer
      - espocrm/espocrm
      - icinga/icinga2
      - mautic/mautic
      - open-webui/open-webui
      - RocketChat/Rocket.Chat
      - taigaio/taiga-back
      - taigaio/taiga-events
      - taigaio/taiga-front
      - WordPress/wordpress-develop
      - zammad/zammad
