feeds:
  - source: github
    repos:
      - composer/composer
      - mautic/mautic
      - RocketChat/Rocket.Chat
      - taigaio/taiga-back
      - taigaio/taiga-events
      - taigaio/taiga-front
      - zammad/zammad
